export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type AppRole = "owner" | "admin" | "operations" | "inspector" | "vendor";
export type PropertyStatus = "active" | "inactive" | "archived";
export type InspectionStatus = "scheduled" | "in_progress" | "completed" | "cancelled";
export type IssueSeverity = "urgent" | "attention" | "monitor";
export type IssueStatus = "open" | "in_progress" | "resolved" | "dismissed";
export type VendorStatus = "active" | "inactive";

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.15" };
  public: {
    Tables: {
      clients: { Row: { created_at:string; display_name:string|null; email:string|null; id:string; legal_name:string; phone:string|null; profile_id:string|null; status:string; updated_at:string }; Insert:{created_at?:string; display_name?:string|null; email?:string|null; id?:string; legal_name:string; phone?:string|null; profile_id?:string|null; status?:string; updated_at?:string}; Update:{created_at?:string; display_name?:string|null; email?:string|null; id?:string; legal_name?:string; phone?:string|null; profile_id?:string|null; status?:string; updated_at?:string}; Relationships:[{foreignKeyName:"clients_profile_id_fkey"; columns:["profile_id"]; isOneToOne:false; referencedRelation:"profiles"; referencedColumns:["id"]}] };
      cpc_billing_events: { Row: { error_message:string|null; event_type:string; id:string; idempotency_key:string; processed_at:string|null; provider:string; provider_event_id:string; received_at:string; status:string }; Insert:{error_message?:string|null; event_type:string; id?:string; idempotency_key:string; processed_at?:string|null; provider:string; provider_event_id:string; received_at?:string; status?:string}; Update:{error_message?:string|null; event_type?:string; id?:string; idempotency_key?:string; processed_at?:string|null; provider?:string; provider_event_id?:string; received_at?:string; status?:string}; Relationships:[] };
      inspection_reports:{ Row:{created_at:string; delivered_at:string|null; finalized_at:string|null; id:string; inspection_id:string; report_data:Json; report_status:string; report_version:number; updated_at:string}; Insert:{created_at?:string; delivered_at?:string|null; finalized_at?:string|null; id?:string; inspection_id:string; report_data?:Json; report_status?:string; report_version?:number; updated_at?:string}; Update:{created_at?:string; delivered_at?:string|null; finalized_at?:string|null; id?:string; inspection_id?:string; report_data?:Json; report_status?:string; report_version?:number; updated_at?:string}; Relationships:[{foreignKeyName:"inspection_reports_inspection_id_fkey"; columns:["inspection_id"]; isOneToOne:true; referencedRelation:"inspections"; referencedColumns:["id"]}] };
      inspections:{ Row:{completed_at:string|null; created_at:string; id:string; inspector_id:string|null; property_id:string; scheduled_for:string; started_at:string|null; status:InspectionStatus; summary:string|null; updated_at:string}; Insert:{completed_at?:string|null; created_at?:string; id?:string; inspector_id?:string|null; property_id:string; scheduled_for:string; started_at?:string|null; status?:InspectionStatus; summary?:string|null; updated_at?:string}; Update:{completed_at?:string|null; created_at?:string; id?:string; inspector_id?:string|null; property_id?:string; scheduled_for?:string; started_at?:string|null; status?:InspectionStatus; summary?:string|null; updated_at?:string}; Relationships:[{foreignKeyName:"inspections_inspector_id_fkey"; columns:["inspector_id"]; isOneToOne:false; referencedRelation:"profiles"; referencedColumns:["id"]},{foreignKeyName:"inspections_property_id_fkey"; columns:["property_id"]; isOneToOne:false; referencedRelation:"properties"; referencedColumns:["id"]}] };
      issues:{ Row:{created_at:string; description:string|null; due_at:string|null; id:string; inspection_id:string|null; property_id:string; reported_by:string|null; resolved_at:string|null; severity:IssueSeverity; status:IssueStatus; title:string; updated_at:string; vendor_id:string|null}; Insert:{created_at?:string; description?:string|null; due_at?:string|null; id?:string; inspection_id?:string|null; property_id:string; reported_by?:string|null; resolved_at?:string|null; severity:IssueSeverity; status?:IssueStatus; title:string; updated_at?:string; vendor_id?:string|null}; Update:{created_at?:string; description?:string|null; due_at?:string|null; id?:string; inspection_id?:string|null; property_id?:string; reported_by?:string|null; resolved_at?:string|null; severity?:IssueSeverity; status?:IssueStatus; title?:string; updated_at?:string; vendor_id?:string|null}; Relationships:[{foreignKeyName:"issues_inspection_id_fkey"; columns:["inspection_id"]; isOneToOne:false; referencedRelation:"inspections"; referencedColumns:["id"]},{foreignKeyName:"issues_property_id_fkey"; columns:["property_id"]; isOneToOne:false; referencedRelation:"properties"; referencedColumns:["id"]},{foreignKeyName:"issues_reported_by_fkey"; columns:["reported_by"]; isOneToOne:false; referencedRelation:"profiles"; referencedColumns:["id"]},{foreignKeyName:"issues_vendor_id_fkey"; columns:["vendor_id"]; isOneToOne:false; referencedRelation:"vendors"; referencedColumns:["id"]}] };
      profiles:{ Row:{created_at:string; full_name:string|null; id:string; phone:string|null; role:AppRole; updated_at:string}; Insert:{created_at?:string; full_name?:string|null; id:string; phone?:string|null; role?:AppRole; updated_at?:string}; Update:{created_at?:string; full_name?:string|null; id?:string; phone?:string|null; role?:AppRole; updated_at?:string}; Relationships:[] };
      properties:{ Row:{access_notes:string|null; address_line_1:string; address_line_2:string|null; city:string|null; client_id:string; created_at:string; id:string; island:string; name:string; postal_code:string|null; status:PropertyStatus; updated_at:string}; Insert:{access_notes?:string|null; address_line_1:string; address_line_2?:string|null; city?:string|null; client_id:string; created_at?:string; id?:string; island?:string; name:string; postal_code?:string|null; status?:PropertyStatus; updated_at?:string}; Update:{access_notes?:string|null; address_line_1?:string; address_line_2?:string|null; city?:string; client_id?:string; created_at?:string; id?:string; island?:string; name?:string; postal_code?:string|null; status?:PropertyStatus; updated_at?:string}; Relationships:[{foreignKeyName:"properties_client_id_fkey"; columns:["client_id"]; isOneToOne:false; referencedRelation:"clients"; referencedColumns:["id"]}] };
      property_contacts:{ Row:{contact_name:string; contact_type:string; created_at:string; email:string|null; id:string; notes:string|null; phone:string|null; property_id:string; updated_at:string}; Insert:{contact_name:string; contact_type:string; created_at?:string; email?:string|null; id?:string; notes?:string|null; phone?:string|null; property_id:string; updated_at?:string}; Update:{contact_name?:string; contact_type?:string; created_at?:string; email?:string|null; id?:string; notes?:string|null; phone?:string|null; property_id?:string; updated_at?:string}; Relationships:[{foreignKeyName:"property_contacts_property_id_fkey"; columns:["property_id"]; isOneToOne:false; referencedRelation:"properties"; referencedColumns:["id"]}] };
      vendors:{ Row:{business_name:string; contact_name:string|null; created_at:string; email:string|null; id:string; phone:string|null; status:VendorStatus; trade:string|null; updated_at:string}; Insert:{business_name:string; contact_name?:string|null; created_at?:string; email?:string|null; id?:string; phone?:string|null; status?:VendorStatus; trade?:string|null; updated_at?:string}; Update:{business_name?:string; contact_name?:string|null; created_at?:string; email?:string|null; id?:string; phone?:string|null; status?:VendorStatus; trade?:string|null; updated_at?:string}; Relationships:[] };
    };
    Views:{[_ in never]:never}; Functions:{[_ in never]:never};
    Enums:{app_role:AppRole; inspection_status:InspectionStatus; issue_severity:IssueSeverity; issue_status:IssueStatus; property_status:PropertyStatus; vendor_status:VendorStatus};
    CompositeTypes:{[_ in never]:never};
  };
};

type DefaultSchema=Omit<Database,"__InternalSupabase">["public"];
export type Tables<Name extends keyof DefaultSchema["Tables"]>=DefaultSchema["Tables"][Name]["Row"];
export type TablesInsert<Name extends keyof DefaultSchema["Tables"]>=DefaultSchema["Tables"][Name]["Insert"];
export type TablesUpdate<Name extends keyof DefaultSchema["Tables"]>=DefaultSchema["Tables"][Name]["Update"];
export type Enums<Name extends keyof DefaultSchema["Enums"]>=DefaultSchema["Enums"][Name];
